# Generated by Django 2.0.4 on 2018-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABO_and_Rh_on_Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo7', models.BooleanField(default=True)),
                ('SampleNo8', models.BooleanField(default=True)),
                ('SampleNo9', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ABO_and_Rh_on_Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo6', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Anti_HCV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo1', models.BooleanField(default=True)),
                ('SampleNo2', models.BooleanField(default=True)),
                ('SampleNo3', models.BooleanField(default=True)),
                ('SampleNo4', models.BooleanField(default=True)),
                ('SampleNo5', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Anti_HIV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo1', models.BooleanField(default=True)),
                ('SampleNo2', models.BooleanField(default=True)),
                ('SampleNo3', models.BooleanField(default=True)),
                ('SampleNo4', models.BooleanField(default=True)),
                ('SampleNo5', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Compatibility_Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo7_and_10', models.BooleanField(default=True)),
                ('SampleNo8_and_11', models.BooleanField(default=True)),
                ('SampleNo9_and_12', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Direct_Anti_globin_Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo6', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Haemoglobin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo6_Sat_or_Not_Sat', models.BooleanField(default=True)),
                ('SampleNo6_Mean_Value', models.IntegerField(default=0)),
                ('SampleNo6_Your_Result', models.IntegerField(default=0)),
                ('SampleNo6_Your_SDI_Value', models.IntegerField(default=0)),
                ('SampleNo7_Sat_or_Not_Sat', models.BooleanField(default=True)),
                ('SampleNo7_Mean_Value', models.IntegerField(default=0)),
                ('SampleNo7_Your_Result', models.IntegerField(default=0)),
                ('SampleNo7_Your_SDI_Value', models.IntegerField(default=0)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HBsAg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo1', models.BooleanField(default=True)),
                ('SampleNo2', models.BooleanField(default=True)),
                ('SampleNo3', models.BooleanField(default=True)),
                ('SampleNo4', models.BooleanField(default=True)),
                ('SampleNo5', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Malaria_Parasite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo6', models.BooleanField(default=True)),
                ('SampleNo7', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Identification_Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo7_and_10', models.BooleanField(default=True)),
                ('SampleNo8_and_11', models.BooleanField(default=True)),
                ('SampleNo9_and_12', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Identification_Scoring_on_Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo7', models.BooleanField(default=True)),
                ('SampleNo8', models.BooleanField(default=True)),
                ('SampleNo9', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Identification_Scoring_on_Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo6', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Syphilis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SampleNo1', models.BooleanField(default=True)),
                ('SampleNo2', models.BooleanField(default=True)),
                ('SampleNo3', models.BooleanField(default=True)),
                ('SampleNo4', models.BooleanField(default=True)),
                ('SampleNo5', models.BooleanField(default=True)),
                ('AchievableScore', models.IntegerField(default=0)),
                ('YourScore', models.IntegerField(default=0)),
            ],
        ),
    ]
