# Generated by Django 2.0.4 on 2018-06-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0002_auto_20180613_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Acells_S7',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Acells_S8',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Acells_S9',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_ABpositive_S7',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_ABpositive_S8',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_ABpositive_S9',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_A_S7',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_A_S8',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_A_S9',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_B_S7',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_B_S8',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_B_S9',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_D_S7',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_D_S8',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Anti_D_S9',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Bcells_S7',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Bcells_S8',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Bcells_S9',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Ocells_S7',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Ocells_S8',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_donors',
            name='Ocells_S9',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_patient_s6',
            name='Acells',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_patient_s6',
            name='Anti_A',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_patient_s6',
            name='Anti_ABpositive',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_patient_s6',
            name='Anti_B',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_patient_s6',
            name='Anti_D',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_patient_s6',
            name='Bcells',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_patient_s6',
            name='Ocells',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='abo_and_rh_on_patient_s6',
            name='serum_reverse_group_method_used',
            field=models.TextField(default='1'),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo7D_and_10R_Additive_37degC',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo7D_and_10R_Additive_Room_temp',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo7D_and_10R_IAHG',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo7D_and_10R_Saline_Room_temp',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo8D_and_11R_Additive_37degC',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo8D_and_11R_Additive_Room_temp',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo8D_and_11R_IAHG',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo8D_and_11R_Saline_Room_temp',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo9D_and_12R_Additive_37degC',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo9D_and_12R_Additive_Room_temp',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo9D_and_12R_IAHG',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='compatibility_testing',
            name='SampleNo9D_and_12R_Saline_Room_temp',
            field=models.CharField(choices=[('n', 'neg'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=40),
        ),
    ]
