# Generated by Django 2.0.4 on 2018-06-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0004_auto_20180621_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beqas',
            name='CutOffValue_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='CutOffValue_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='CutOffValue_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='CutOffValue_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='MethodUsed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Methodology_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Methodology_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Methodology_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Methodology_Haemoglobin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Methodology_Malaria_Parasite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Methodology_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Result_S6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Result_S7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Result_S8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Result_S9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo1_OD_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo1_OD_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo1_OD_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo1_OD_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo1_Result_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo1_Result_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo1_Result_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo1_Result_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo2_OD_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo2_OD_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo2_OD_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo2_OD_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo2_Result_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo2_Result_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo2_Result_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo2_Result_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo3_OD_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo3_OD_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo3_OD_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo3_OD_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo3_Result_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo3_Result_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo3_Result_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo3_Result_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo4_OD_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo4_OD_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo4_OD_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo4_OD_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo4_Result_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo4_Result_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo4_Result_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo4_Result_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo5_OD_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo5_OD_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo5_OD_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo5_OD_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo5_Result_Anti_HCV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo5_Result_Anti_HIV',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo5_Result_HBsAg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo5_Result_Syphilis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo6_Haemoglobin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo6_Malaria_Parasite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo7_Haemoglobin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='SampleNo7_Malaria_Parasite',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Specifiy_additive',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='Specifiy_other_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='cft_method_ABO_and_Rh_on_Donors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='cft_method_ABO_and_Rh_on_Patient_S6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='beqas',
            name='srgMethod_ABO_and_Rh_on_Donors',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
