# Generated by Django 2.0.4 on 2018-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0005_auto_20180621_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beqas',
            name='patientId',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
