# Generated by Django 2.0.4 on 2018-06-21 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0006_auto_20180621_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beqas',
            name='patientId',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
