# Generated by Django 2.0.4 on 2018-06-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0007_auto_20180621_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beqas',
            old_name='cft_method_ABO_and_Rh_on_Donors',
            new_name='method_ABO_and_Rh_on_Donors',
        ),
        migrations.RemoveField(
            model_name='beqas',
            name='srgMethod_ABO_and_Rh_on_Donors',
        ),
        migrations.RemoveField(
            model_name='beqas',
            name='srgMethod_S6',
        ),
    ]
