# Generated by Django 2.0.4 on 2018-06-28 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0008_auto_20180626_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beqassearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patId', models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
