# Generated by Django 2.0.4 on 2018-06-28 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0009_beqassearch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beqassearch',
        ),
    ]
