# Generated by Django 2.0.4 on 2018-07-09 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0010_delete_beqassearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='beqas',
            name='cycleno',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='beqas',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
