# Generated by Django 2.0.4 on 2018-07-09 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0011_auto_20180709_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beqas',
            name='date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
