# Generated by Django 2.0.4 on 2018-07-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ircs', '0013_auto_20180709_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beqas',
            name='date',
        ),
        migrations.AddField(
            model_name='beqas',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
